name: Download transcript

on:
  # Run daily at 07:00 Hobart (AEST = UTC+10). Adjust as needed, or delete this block.
  schedule:
    - cron: "0 21 * * *"   # 21:00 UTC ≈ 07:00 AEST
  workflow_dispatch:
    inputs:
      query:
        description: 'Search text, e.g. "House of Assembly Tuesday 19 August 2025"'
        required: false
      keywords:
        description: 'Optional comma-separated keywords for digest (overrides keywords.txt)'
        required: false

permissions:
  contents: write   # needed to commit the downloaded file back to the repo

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      WAIT_BEFORE_DOWNLOAD_SECONDS: "15"
      PARAGRAPH_RADIUS: "0"         # set to "1" to include neighboring paragraphs in digest
      KEYWORDS: "${{ github.event.inputs.keywords }}"  # optional override
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Playwright (Python) + browser + email lib
        run: |
          python -m pip install --upgrade pip
          python -m pip install playwright yagmail
          python -m playwright install chromium

      - name: Determine search term (scheduled vs manual)
        id: term
        run: |
          if [ -n "${{ github.event.inputs.query }}" ]; then
            echo "SEARCH_TERM=${{ github.event.inputs.query }}" >> $GITHUB_ENV
          else
            TZ="Australia/Hobart" date "+House of Assembly %A %-d %B %Y" > term.txt
            echo "SEARCH_TERM=$(cat term.txt)" >> $GITHUB_ENV
          fi
          echo "Using search term: $SEARCH_TERM"

      - name: Download transcript
        run: |
          python download_transcript.py "$SEARCH_TERM"

      - name: Send email (digest + attachment)
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO:   ${{ secrets.EMAIL_TO }}
        run: |
          python send_email.py

      - name: Commit downloaded transcript
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add transcripts/*.txt || echo 'No transcripts'
          git commit -m "Add transcript for $SEARCH_TERM" || echo 'No changes'
          git push

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hansard-output
          path: |
            transcripts/*.txt
            digest_*.txt
